In [70]:
from numpy import array, sin, cos, sqrt, cross, dot, pi, linspace
import pyrr.matrix33 as m3
import pyrr.matrix44 as m4
r = 2.0
l = 3.0
h = 1.5


tl = 1.1
tr = 1.0



Dgtl = array((-h, sqrt(r**2 - h**2)-r+l/2))
Dgtr = array((h, sqrt(r**2 - h**2)-r+l/2))
Dgbl = array((-h, -sqrt(r**2 - h**2)+r-l/2))
Dgbr = array((h, -sqrt(r**2 - h**2)+r-l/2))


In [51]:
# ring 0
t0 = 0.10798839622442215/2

Tbl0 = tl*array((-sin(t0),-cos(t0)))
Tbr0 = tr*array((-sin(t0),-cos(t0)))
R0 = -(Tbl0 + Tbr0)
Dcb0 = array((-r*sin(t0), -r*cos(t0)+r-l/2))


m0 = cross(Dcb0, R0) + cross(Dgbl, Tbl0) + cross(Dgbr, Tbr0)
print(m0)

-0.00014370862708235066


In [56]:
T1tl = tl*array((-sin(t0),cos(t0)))
T1tr = tr*array((-sin(t0),cos(t0)))
R1t = dot(m3.create_from_axis_rotation((1.0,0,0), 2*t0), -array((0, R0[0],R0[1])))[1:]
D1ct = array((-r*sin(t0), r*cos(t0)+l/2-r))

t1 = 0.848062078981481/2
# x = linspace(-pi/5, pi/5)
# y = []
# for t1 in x:
T1bl = tl*array((-sin(t1),-cos(t1)))
T1br = tr*array((-sin(t1),-cos(t1)))
R1 = -(T1tl + T1tr + R1t + T1bl +T1br)
D1cb = array((-r*sin(t1), -(r*cos(t1)+l/2-r)))
m1 = cross(D1ct, R1t) 
# cross(D1cb,R1) + cross(Dgbl, T1bl) + cross(Dgbr, T1br) + cross(Dgtl, T1tr)  + cross(Dgtr, T1tr) + 
    # y.append(m1)
cross(Dgtl, T1tl)+ cross(Dgtr, T1tr)+cross(D1ct, R1t) + cross(Dgbl, T1bl) + cross(Dgbr, T1br) + cross(D1cb,R1)

0.2859870423867714

In [93]:
import pyrr
theta = 0.054180
a = array((0,0.169, 2.098), )


m = m3.create_from_axis_rotation(array((1.0,0,0),order="F"), 0.054180)
mt = m4.create_from_translation((2,1,3))
print(mt)
# print(dot(mt.transpose(),a))
# m.transpose().flags
# a.flags
# m4.multiply(m,a.reshape((3,1)))

# a.reshape((3,1))
# m = m3.create_from_axis_rotation((1.0,0,0), 0.054180)

# v = array(((cos(theta), -sin(theta)), (sin(theta), cos(theta))))
# (m,v)
import numpy as np
a = array((1,2,3),dtype=np.float32)
(a*1.0).dtype

[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [2 1 3 1]]


dtype('float32')